//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auteur()
        {
            this.Participer = new HashSet<Participer>();
        }
    
        public int IdAuteur { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string Biographie { get; set; }
        public string Telephone { get; set; }
    
        public virtual Auteur Auteur1 { get; set; }
        public virtual Auteur Auteur2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participer> Participer { get; set; }
    }
}
