//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailCommande
    {
        public int IdCommande { get; set; }
        public int IdLivre { get; set; }
        public Nullable<int> Nombre { get; set; }
        public Nullable<decimal> Prix { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Commande Commande1 { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
