//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livre()
        {
            this.DetailCommande = new HashSet<DetailCommande>();
            this.Participer = new HashSet<Participer>();
        }
    
        public int IdLivre { get; set; }
        public string NomLivre { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public string Photo { get; set; }
        public Nullable<int> NombreReste { get; set; }
        public Nullable<int> IdSujet { get; set; }
        public Nullable<int> IdEdition { get; set; }
        public Nullable<int> Nouveau { get; set; }
        public byte[] BackgroundFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailCommande> DetailCommande { get; set; }
        public virtual Edition Edition { get; set; }
        public virtual Sujet Sujet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participer> Participer { get; set; }
    }
}
