//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participer
    {
        public int IdLivre { get; set; }
        public int IdAuteur { get; set; }
        public string Role { get; set; }
        public string Position { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
